
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: record_audio
  username: akshay
  password: akshay@1A
  host: localhost
  port: 5432

  test:
  <<: *default
  database: voice_transcription_app_test


production:
  primary: &primary_production
    <<: *default
    database: voice_transcription_app_production
    username: voice_transcription_app
    password: <%= ENV["VOICE_TRANSCRIPTION_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: voice_transcription_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: voice_transcription_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: voice_transcription_app_production_cable
    migrations_paths: db/cable_migrate
